# access_key        = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
# secret_key        = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXxx"
access_key        = "AKIA23E6DTVGSJHJMHG2"
secret_key        = "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"
instance_type     = "t2.micro"
availability_zone = "eu-west-3a"
region            = "eu-west-3"
